#pragma once

namespace Omotura
{
	enum class API
	{
		OPENGL
	};

	#define ATTRIBUTE_POSITION_LOCATION 0
	#define ATTRIBUTE_NORMAL_LOCATION 1
	#define ATTRIBUTE_TEX_COORD_LOCATION 2
	#define ATTRIBUTE_BONE_ID_LOCATION 3
	#define ATTRIBUTE_BONE_WEIGHT_LOCATION 4

	#define TEXTURE_UNIT_DIFFUSE GL_TEXTURE0
	#define TEXTURE_UNIT_NORMAL GL_TEXTURE1
	#define TEXTURE_UNIT_RMA GL_TEXTURE2
}